    opp_time_bonus = '+ ' + str(opp_time_bonus) + ' x 10'
    opp_sabotage_penalty = '- ' + str(opp_sabotage_penalty) + ' x 10'
    opp_excellency_bonus = '+ ' + str(int(opp_excellency_bonus))
    opp_score = str(int(opp_score)) + ' s'
    scorefont = pygame.font.Font('Bukhari Script.ttf', 72)
    finalfont = pygame.font.Font('Bukhari Script.ttf', 120)
    msg_opp_time_bonus = scorefont.render(str(opp_time_bonus),False,(236, 233, 218))
    msg_opp_time_bonus2 = scorefont.render(str(opp_time_bonus),False,(187, 56, 49))
    msg_opp_excellency_bonus = scorefont.render(str(opp_excellency_bonus),False,(236, 233, 218))
    msg_opp_excellency_bonus2 = scorefont.render(str(opp_excellency_bonus),False,(187, 56, 49))
    msg_opp_sabotage_penalty = scorefont.render(str(opp_sabotage_penalty),False,(236, 233, 218))
    msg_opp_sabotage_penalty2 = scorefont.render(str(opp_sabotage_penalty),False,(187, 56, 49))
    msg_opp_score = scorefont.render(str(opp_score),False,(236, 233, 218))
    msg_opp_score2 = scorefont.render(str(opp_score),False,(187, 56, 49))
    msg_opp_finalscore = finalfont.render(str(opp_final_score), False, (236, 233, 218))